
name: Docker CI
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-container:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: publish to github package
        uses: docker/build-push-action@v2

          
      - name: publish to docker hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: chandan0312/github_action_docker
          repository: ${{ github.repository }}/next
          tags: latest, ${{ github.run_number }}
        
